language: node_js
node_js:
- "10.3"
cache:
  yarn: true
services:
- postgresql
env:
  global:
  - secure: TODO
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --frozen-lockfile
before_script:
- psql -c 'CREATE DATABASE spoke_test;' -U postgres
- psql -c "CREATE USER spoke_test WITH PASSWORD 'spoke_test';" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE spoke_test TO spoke_test;' -U postgres
script:
- yarn test
- CC_TEST_RESULT1=$?
- yarn test-sqlite
- CC_TEST_RESULT2=$?
after_script:
- ./cc-test-reporter after-build --exit-code $(( $CC_TEST_RESULT1 && $CC_TEST_RESULT2 ))

